<?php
/**
 * Copyright © MagePal LLC. All rights reserved.
 * See COPYING.txt for license details.
 * https://www.magepal.com | support@magepal.com
 */

/**
 * @var $block MagePal\CheckoutSuccessMiscScript\Block\Adminhtml\System\Config\Form\Field\MiscScript
 */
?>

<?php
$_htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
$_colspan = $block->isAddAfter() ? 2 : 1;
?>

<div class="design_theme_ua_regexp" id="grid<?= $block->escapeHtmlAttr($_htmlId) ?>">
    <div class="admin__control-table-wrapper">
        <table class="admin__control-table" id="<?= $block->escapeHtmlAttr($block->getElement()->getId()) ?>">
            <thead>
                <tr>
                    <?php foreach ($block->getColumns() as $columnName => $column) : ?>
                        <?php if ($column['type'] != 'textarea') :?>
                        <th><?= $block->escapeHtml($column['label']) ?></th>
                        <?php endif; ?>
                    <?php endforeach;?>
                    <th class="col-actions" colspan="<?= $block->escapeHtmlAttr($_colspan) ?>">
                        <?= $block->escapeHtml(__('Action')); ?>
                    </th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="<?= count($block->getColumns())+$_colspan ?>" class="col-actions-add">
                        <button id="addToEndBtn<?= $block->escapeHtmlAttr($_htmlId) ?>"
                                class="action-add"
                                title="<?= $block->escapeHtmlAttr(__('Add')) ?>"
                                type="button">
                            <span><?= $block->escapeHtml($block->getAddButtonLabel()) ?></span>
                        </button>
                    </td>
                </tr>
            </tfoot>
            <tbody id="addRow<?= $block->escapeHtmlAttr($_htmlId) ?>"></tbody>
        </table>
    </div>
    <input type="hidden"
           name="<?= $block->escapeHtmlAttr($block->getElement()->getName()) ?>[__empty]"
           value="" />

    <script>
        require([
            'mage/template',
            'jquery',
            'prototype'
        ], function (mageTemplate, $j) {
            // create row creator
            window.arrayRow<?= /* @noEscape */ $_htmlId ?> = {

                // define row prototypeJS template
                template: mageTemplate(
                        '<tr id="<%- _id %>">'
                        <?php foreach ($block->getColumns() as $columnName => $column) : ?>
                            <?php if ($column['type'] != 'textarea') :?>
                                + '<td>'
                                + '<?= /* @noEscape */  $block->renderCellTemplate($columnName) ?>'
                                + '<\/td>'
                            <?php endif; ?>
                        <?php endforeach; ?>

                        <?php if ($block->isAddAfter()) : ?>
                                + '<td><button class="action-add" type="button" id="addAfterBtn<%- _id %>"><span><?= $block->escapeHtml(__('Add after')) ?><\/span><\/button><\/td>'
                        <?php endif; ?>

                                + '<td class="col-actions"><button onclick="arrayRow<?= /* @noEscape */ $_htmlId ?>.del(\'<%- _id %>\')" class="action-delete" type="button"><span><?= $block->escapeHtml(__('Delete')) ?><\/span><\/button><\/td>'
                                +'<\/tr>'

                        <?php foreach ($block->getColumns() as $columnName => $column) : ?>
                            <?php if ($column['type'] == 'textarea') :?>
                            + '<tr id="<%- _id %>"><td colspan="<?= count($block->getColumns())+$_colspan ?>">'
                            + '<?= /* @noEscape */  $block->renderCellTemplate($columnName) ?>'
                            + '<div><?= /* @noEscape */ $block->getTemplateButtonList() ?></div>'
                            + '<\/td></tr>'
                            <?php endif; ?>
                        <?php endforeach; ?>
                ),

                add: function(rowData, insertAfterId) {
                    // generate default template data
                    var templateValues;

                    // Prepare template values
                    if (rowData) {
                        templateValues = rowData;
                    } else {
                        var d = new Date();
                        templateValues = {
                            <?php foreach ($block->getColumns() as $columnName => $column) : ?>
                                <?= /* @noEscape */ $columnName ?> : '',
                                'option_extra_attrs': {},
                            <?php endforeach; ?>
                            _id: '_' + d.getTime() + '_' + d.getMilliseconds()
                        };
                    }

                    // Insert new row after specified row or at the bottom
                    if (insertAfterId) {
                        Element.insert($(insertAfterId), {after: this.template(templateValues)});
                    } else {
                        Element.insert($('addRow<?= /* @noEscape */ $_htmlId ?>'), {bottom: this.template(templateValues)});
                    }

                    // Fill controls with data
                    if (rowData) {
                        var rowInputElementNames = Object.keys(rowData.column_values);
                        for (var i = 0; i < rowInputElementNames.length; i++) {
                            if ($(rowInputElementNames[i])) {
                                $(rowInputElementNames[i]).setValue(rowData.column_values[rowInputElementNames[i]]);
                            }
                        }
                    }

                    // Add event for {addAfterBtn} button
                    <?php if ($block->isAddAfter()) : ?>
                    Event.observe('addAfterBtn' + templateValues._id, 'click', this.add.bind(this, false, templateValues._id));
                    <?php endif; ?>

                    $j('#magepal_checkout_misc_script_scripts').trigger('contentUpdated');
                },

                del: function(rowId) {
                    $(rowId).remove();
                    $(rowId).remove();
                }
            };

            // bind add action to "Add" button in last row
            // phpcs:disable
            Event.observe('addToEndBtn<?= /* @noEscape */  $_htmlId ?>', 'click', arrayRow<?= /* @noEscape */  $_htmlId ?>.add.bind(arrayRow<?= /* @noEscape */ $_htmlId ?>, false, false));
            // phpcs:enable

            // add existing rows
            <?php foreach ($block->getArrayRows() as $_rowId => $_row) : ?>
                <?= /* @noEscape */ "arrayRow{$_htmlId}.add(" . $_row->toJson() . ");\n"; ?>
            <?php endforeach; ?>

            // Toggle the grid availability, if element is disabled (depending on scope)
            <?php if ($block->getElement()->getDisabled()) :?>
            toggleValueElements({checked: true}, $('grid<?= /* @noEscape */ $_htmlId ?>').parentNode);
            <?php endif;?>
        });
    </script>
</div>
